version: '3.8'

services:
  backend:
    build: ./backend  # Point to the new backend directory
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app  # Map the new backend directory to /app in the container
      - /app/node_modules  # Ensure node_modules is handled correctly
    environment:
      - NODE_ENV=development
    depends_on:
      - kafka
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app  # Volume for frontend project files
      - /app/node_modules
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock